#4 Use type icons as map markers
jri/dm5-geomaps pull request #1
Opened 2020-12-17 19:54 UTC by gevlish

Hi @jri, here's the branch. 
Now that I see the final code it looks very simple, sorry it took me so long, only leaflet had its own tricky part but
I hope everything's in order. Please let me know your comments.
cheers, 
gloria

2020-12-19 22:38 UTC, jri requested changes

2020-12-19 22:38 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +    setTimeout( () => {
When I remove the `setTimeout()` the browser shows an error:

![image](https://user-images.githubusercontent.com/120337/102700130-12c7da80-424b-11eb-82a1-55326f0074c6.png)

`geoMarkers` is undefined because the `geomap` has not yet arrived. It arrives asynchronously.

We can't create the icons here in `mounted()`. This is too early.
We need a watcher instead.

=> Watch `geomap` and call your create-icon code there.
=> Add a `createIcons()` method and move the create-icon code here. (`mounted()` is not needed)
=> Remove `setTimeout()`

Background: in the old Geomaps plugin marker rendering is purely declarative/reactive. Vue's data binding does the whole job.

Your situation is different: you need to execute code (`createIcons()`) when data change (`geomap`). This is because `createIcons()` involves asynchronicity (the single SVG request).

If no asynchronicity would be involved you could put the create-code into a computed property, and that's it. No watcher would be required.

Hint: the browser shows the Vue warning only when the Webclient runs in dev mode.

Your code is basically correct. 👍 Asynchronicity was not adequately handled though.

This is a great opportunity to learn about asynchronicity, computed properties and watchers.

@gevlish Please tell me if you have questions/remarks.

2020-12-21 14:30 UTC, jri requested changes
@gevlish Gloria, how are you?
I hope my change requests find you in a good mood.

Here I like to tackle messaging. A geomap is supposed to display new markers without a page reload. This is done via (WebSocket) messaging. It worked in the old Geomaps plugin. For the new one work is still required.

Try this:
1. Switch to a geomap
2. Switch back to a normal map
3. Create a Person, enter its Address (a City is sufficient), and press Save.

Now the browser console shows an error:

![image](https://user-images.githubusercontent.com/120337/102782801-3b121f00-439a-11eb-8152-96967c479d2c.png)

(When you switch back to the geomap the new marker does not appear.)

This is because Geomaps messaging is not yet adapted to the new Geomaps serialization format (markers, domain topics).

=> At server side adapt message generation [here](https://github.com/dmx-systems/dmx-geomaps/blob/master/src/main/java/systems/dmx/geomaps/GeomapsPlugin.java#L472)
=> At client side adapt message processing [here](https://github.com/dmx-systems/dmx-geomaps/blob/master/src/main/js/geomaps.js#L10)

A DMX websocket message is an object with 2 props: `type` (string) and `args` (anything you want). The Webclient processes a WebSocket message by dispatching a Vuex action. The action name is the message type, prepended by `_`. The action's payload is the message args.

Note that messaging is not used only for Geomap's Client-Sync feature (see task description) but also for updating the user's own Webclient state.

Tell me if you need more info!

This 2nd change request will be the last major one. The remaining ones will be more simple. 😄

2020-12-21 18:31 UTC, gevlish commented
Hi @jri Jörg, fine thanks, yep, very good mood 😎

So, yesterday I was reading all your comments and as you point out today (you're always one step ahead 😀) I also found that the problem was that the newCoords are not update to the new geomap construction, I corrected the code, but it is not only update the coords, the domainTopics also need to be there to pass the values to the stateGeomap,  I tried to import the getDomainTopic function, but it is not recognized, I'm working on it.

About the watcher, I know getting the icons happens asynchronous but when i tried before with the watcher it is also needed to trigger an event to update the map, in l-map you can use the 'ready' property or when the update:zoom or update:center happens but is not happen right away and when you change from the map to the workspace and return to the map the icons are not there you have to move or  zoom the map for them to appear again, that's why i used the setTime.
What i did now to remove it is call the event with the geoMap refs but this is also happens when the map is mounted

`if (this.$refs.geomapRef.ready) {
      this.createIcons()
    }`

Thanks, let me know your comments

2020-12-28 17:08 UTC, jri commented
Dear @gev, please excuse the late reply.

> [...] when you change from the map to the workspace and return to the map the icons are not there [...]

Confirmed!

> What i did now to remove it is call the event with the geoMap refs but this is also happens when the map is mounted
>
>       if (this.$refs.geomapRef.ready) { this.createIcons() }

Here I don't understand what you've tried, and if you need more help.

From my perspective, and inspired by the `ready` event you've mentioned, this is what works for me (both, dev mode and production mode):

```
  <l-map ... @ready="ready">

  watch: {
    geomap () {
      this.createIcons()
    }
  },

  methods: {
    ready () {
      if (this.geomap) {
        this.createIcons()
      }
    }
  }
```

The watcher handles initial geomap rendering. The`ready` handler handles subsequent rendering (when switching back to a geomap). In each case `createIcons()` is called exactly once. 
Using `$refs` is not required.

In case this works for you please add a commit to your pull request.

2020-12-28 18:31 UTC, gevlish commented
Hi @jri, thanks, yes the 'ready' method is also working for me. I thought it differently but it is better with your option.

About my comment https://git.dmx.systems/dmx-plugins/dmx-geomaps/-/issues/4#note_17662, I ended up getting the domainTopic with the assoc in the vue component by taking advantage of the markers construction to make the icon work on production I don't know if this is the right solution but it is working nice.
And it is not neccesary to change anything at GeomapsPlugin, although I still have the doubt if it's possible to do it on the server side

I did another commit to the pull request. By the way I didn't know if I have to do this new commit or replace the files of the first one. 😁. I'm still getting familiar with the requests.

Please let me know your comments.

2020-12-29 13:25 UTC, gevlish commented
Hi @jri, I made a mistake in the code of the dmx-geomaps-render-vue file of the previous commit, I fixed it and also change the `createIcons() ` conditionals to switch/case. Please check the last one. Thanks!

2021-01-02 13:09 UTC, jri requested changes

2021-01-02 13:09 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +import dmx from 'dmx-api'
@gevlish In a plugin you must never import `dmx-api` but rely on dependency injection instead. See this [forum posting](https://forum.dmx.systems/t/implementing-custom-commands-with-plugin-js-utilizing-webclient-state-and-the-dmx-api/99/4?u=jri) (it is about importing `Vue` but actually applies to all Webclient dependencies, `Vue`, `dmx-api`, ...).

2021-01-02 13:24 UTC, jri requested changes

2021-01-02 13:24 UTC, jri commented on src/main/java/systems/dmx/geomaps/Geomap.java
> +    }
@gevlish you could use `DMXUtils.toJSONArray(domainTopics.values())` instead of cooking your own. But this is not in use anyways. Consider dropping your `listToJSON()` method.

2021-01-02 13:46 UTC, jri requested changes

2021-01-02 13:46 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +        iconUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1792"%3E%3Cpath fill="%234B87C3" d="M768 640q0 -106 -75 -181t-181 -75t-181 75t-75 181t75 181t181 75t18
@gevlish here you've code doubling, which should be removed. Instead of constructing a SVG-URL manually you should call `getSVGUrl()` instead, passing an Unicode value (`f041` as it seems).

The supposed (single) responsibility of the `getSVGUrl()` method is constructing a SVG-URL from a Unicode value. So you never must construct them manually.

=> Refactor `getSVGUrl()` method. Call it *whenever* you need construct a SVG-URL. In particular call it for both, regular map markers, and "multi-spot" map marker.

If you need higher-level logic, e.g. constructing L.Icon objects fom a SVG-URL, consider wrapping that method in another one.

=> Make yourself familiar with the **single-responsibility principle** and the **DRY-rule**.

2021-01-02 16:02 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +        iconUrl: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1792"%3E%3Cpath fill="%234B87C3" d="M768 640q0 -106 -75 -181t-181 -75t-181 75t-75 181t75 181t181 75t18
BTW: happy new year! 😎

2021-01-05 14:20 UTC, jri requested changes

2021-01-05 14:20 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> -            const height = 20    // markers are too small, recalculate??
@gevlish Hint: the geometry numbers I gave you are just examples. If the icons are too small feel free to increase the scaling factor (`0.009`). Make sure you get all appearances. Consider introducing a constant (e.g. `ICON_SCALING`).

2021-01-05 19:50 UTC, gevlish commented
Hi @jri, I made the changes to the icon size. 

I have a HELP 😁 question here, I tried to update the files with the last changes of dmx-geomaps plugin using `git merge upstream/master` to keep the fork in my repository update, but I replaced my localfiles 😢 (the geomapsIcons branch). I have a backup, but how can I clone only the branch to restore the files in the same local folder? So I can continue commiting from there, or should I just replace the files with my backup?

BTW because I made the changes in github now there's a conflict in the branch.

2021-01-05 20:13 UTC, jri commented
I've resolved the merge conflict. You can `git pull` now.

2021-01-05 20:33 UTC, jri commented
>  I replaced my localfiles

Have you lost uncomitted changes? Only your backup can bring them back then.
BTW: `git stash` is useful to keep uncomitted changes e.g. before merging.

Otherwise you can reset and update your working tree:
```
git reset --hard
git pull
```

Meanwhile I've resolved the merge conflict at GitHub, so you should have an up-to-date working tree.

2021-01-05 20:56 UTC, gev commented
> Dear @gev, please excuse the late reply.

I'm so sorry! Do you mean @gevlish ? =)

PS  But I'd interesting in this theme some years ago =) I mean mind maps, OSM, RDF, OWL and so. Even mapped the my city for the OSM

2021-01-05 21:22 UTC, jri commented
Oh, sorry, @gev for involving you here. Apparently it was a mistake. But who can know 😄

2021-01-05 21:23 UTC, gevlish commented
> Have you lost uncomitted changes? Only your backup can bring them back then.
> BTW: `git stash` is useful to keep uncomitted changes e.g. before merging.

No, everything has been committed, the backup just have some extra comments.
 I used `git pull origin geomapsIcons` and recover the state. Thanks a lot!

2021-01-05 21:25 UTC, gev commented
> Oh, sorry, @gev for involving you here. Apparently it was a mistake. But who can know 😄

It was fun! Just remembering last years, when I have interested in semantic too

2021-01-06 18:29 UTC, jri requested changes

2021-01-06 18:29 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +            switch (true) {
`switch (true)` is very unorthodox. Most readers will be puzzled by that. Where did you get it?

=> Please replace the switch with a regular if-else.

2021-01-06 20:06 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +// })
Very good you've spotted this workaround is no longer necessary 👍

2021-01-07 22:37 UTC, jri requested changes

2021-01-07 22:37 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +        this.dmx.icons.ready.then(() => {
It is sufficient to register the success handler *once* per `createIcons()` call. At the moment another handler is registered for *every* loop iteration!

=> Please move `this.dmx.icons.ready.then(` out of the loop.

2021-02-12 15:06 UTC, jri commented
@gevlish thank you very much for yesterday's video chat! Meanwhile platform's master branch provides you the facilities as discussed. Note that the parameter of the postUpdate handler have changed:

Example usage:
```java
import systems.dmx.core.service.ChangeReport;

    @Override
    public void postUpdateTopic(Topic topic, ChangeReport report, TopicModel updateModel) {
        logger.info(">>>>> report=" + report);
        if (topic.getTypeUri().equals(PERSON) || topic.getTypeUri().equals(ORGANIZATION)) {
            List<ChangeReport.Change> changes = report.getChanges(ADDRESS + "#" + ADDRESS_ENTRY);
            if (changes != null) {
                for (ChangeReport.Change change : changes) {
                    TopicModel oldValue = change.oldValue;
                    TopicModel newValue = change.newValue;
                    if (oldValue == null) {
                        // send add-domain-topic message
                    } else if (newValue == null) {
                        // send remove-domain-topic message
                    } else {
                        // send add-domain-topic message
                        // send remove-domain-topic message
                    }
                }
            }
        }
    }

```
Cheers!

2021-02-23 12:47 UTC, jri commented
@gevlish as discussed in a `ChangeReport` `newValue`/`oldValue` are now of type `Topic` (was `TopicModel`). So please update platform and adapt your code accordingly. Your code will get more simple 😄

2021-03-16 23:01 UTC, jri commented on src/main/java/systems/dmx/geomaps/GeomapsPlugin.java
> +    private boolean hasAddressChildType(DMXType type) {
Please move private methods to "private" section below.
Usually we do forward-references: use it before declare it (if in same file)

2021-03-16 23:01 UTC, jri commented on src/main/java/systems/dmx/geomaps/GeomapsPlugin.java
> +          if (hasAddressChildType(topic.getType())) {
Please make `hasAddressChildType()` to return CompDef or `null` instead of boolean

2021-03-16 23:01 UTC, jri commented on src/main/java/systems/dmx/geomaps/GeomapsPlugin.java
> +          Topic domainTopic = dmx.getTopic(topic.getId());
Note that `dmx.getTopic()` is a DB access you don't need. `topic` is the domain topic already. So you could write `Topic domainTopic = topic` but actually, not that at this moment we don't know if this is a domain topic at all.

2021-03-18 01:59 UTC, gevlish commented on src/main/java/systems/dmx/geomaps/GeomapsPlugin.java
> +          Topic domainTopic = dmx.getTopic(topic.getId());
I used dmx.getTopic() just to pass the domainTopic without the children. Is that ok or should I remove it?

2021-03-19 19:50 UTC, jri requested changes

2021-03-19 19:50 UTC, jri commented on src/main/java/systems/dmx/geomaps/GeomapsPlugin.java
> +          Topic domainTopic = dmx.getTopic(topic.getId());
Please do it w/o `dmx.getTopic()`:

```java
          CompDef compDef = hasAddressChildType(topic.getType());
          if (compDef != null) {
              Topic domainTopic = topic;
              logger.info("@@@ domainTopic: " + domainTopic);

```

2021-03-19 19:50 UTC, jri commented on src/main/java/systems/dmx/geomaps/GeomapsPlugin.java
> +              List<ChangeReport.Change> changes = report.getChanges(ADDRESS + "#" + ADDRESS_ENTRY);
Please adapt the compDefUri:
```java
              List<ChangeReport.Change> changes = report.getChanges(compDef.getCompDefUri());
```

2021-03-25 21:55 UTC, jri requested changes

2021-03-25 21:55 UTC, jri commented on src/main/js/components/dmx-geomap-renderer.vue
> +      })
@gevlish ... and can you please set anchor options for the popup as well?

SNAPSHOT:

![image](https://user-images.githubusercontent.com/120337/112548465-93ebbc00-8dbc-11eb-8dd9-8505872b5446.png)

Original:

![image](https://user-images.githubusercontent.com/120337/112548340-5be47900-8dbc-11eb-82b8-b360e496c2b1.png)

2021-03-29 12:56 UTC, merged